name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem are you trying to solve? Is this related to a frustration with the current behavior?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've tried...

  - type: textarea
    id: code
    attributes:
      label: Example Code
      description: If applicable, show how you'd like the API to work
      render: python
      placeholder: |
        # Proposed API
        from integradio import new_feature

        result = new_feature(...)

  - type: dropdown
    id: scope
    attributes:
      label: Feature Scope
      description: Which part of integradio would this affect?
      options:
        - Core (SemanticBlocks, components)
        - Embedder (Ollama integration)
        - Registry (search, storage)
        - Pages (pre-built templates)
        - Events (WebSocket, mesh)
        - Visual (design tokens, themes)
        - API (FastAPI routes)
        - Visualization (Mermaid, D3.js)
        - Other
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to help implement this feature
